Repository arangodb-helper/arangodb, pull requests merged in 2018-04, with the labels that each got.

#133 Doc - fixes the build
  docs/Manual/Programs/Starter/Options.md
Labels: 9 Ready to Merge

#135 Updated golang to 1.10.1, force pull ARANGODB images in travis docker test
  Makefile
  test/docker_single_test.go
Labels: 9 Waiting for Jenkins

#136 Specified upgrade version procedure
  docs/upgrade_spec.md
Labels: 9 Review Required

#137 Database auto upgrade support
  CHANGELOG.md
  Makefile
  docs/http_api.md
  service/arangod/agency_health.go
  service/arangod/api.go
  service/arangod/client.go
  service/arangod/error.go
  service/arangod/lock.go
  service/arangod/lock_errors.go
  service/arangod/multi_client.go
  service/arangod_config_builder.go
  service/cluster_config.go
  service/mode.go
  service/runtime_server_manager.go
  service/server.go
  service/server_config_builder.go
  service/service.go
  service/upgrade_manager.go
  vendor/github.com/ryanuber/columnize/.travis.yml
  vendor/github.com/ryanuber/columnize/LICENSE
  vendor/github.com/ryanuber/columnize/README.md
  vendor/github.com/ryanuber/columnize/columnize.go
  vendor/github.com/ryanuber/columnize/columnize_test.go
Labels: 9 Review Required

#140 Added `--starter.host` option
  CHANGELOG.md
  docs/Manual/Programs/Starter/Options.md
  main.go
  service/service.go
Labels: 9 Review Required

#144 Fixed docker test image (wrt alpine) used for running local-process tests
  Makefile
  test/Dockerfile-arangodb-golang
  test/docker_install_go.sh
Labels: 9 Waiting for Jenkins

#145 Fix tests of activefailover
  Makefile
  service/error.go
  service/runtime_server_manager.go
  service/service.go
  test/docker_activefailover_default_test.go
  test/docker_activefailover_local_test.go
  test/docker_cluster_default_test.go
  test/docker_cluster_diff_logdir_test.go
  test/docker_cluster_diff_ports_test.go
  test/docker_cluster_local_test.go
  test/docker_cluster_multi_join_test.go
  test/docker_cluster_recovery_test.go
  test/docker_cluster_sync_test.go
  test/docker_resilientsingle_default_test.go
  test/docker_resilientsingle_local_test.go
  test/docker_single_test.go
  test/process_activefailover_default_test.go
  test/process_cluster_default_test.go
  test/process_cluster_diff_logdir_test.go
  test/process_cluster_diff_ports_test.go
  test/process_cluster_local_test.go
  test/process_cluster_multi_join_test.go
  test/process_cluster_recovery_test.go
  test/process_cluster_sync_test.go
  test/process_resilientsingle_default_test.go
  test/process_single_test.go
  test/util.go
Labels: 9 Waiting for Jenkins

#152 Switch algorithme for auto-generated TLS certificates from RSA to ECDSA
  CHANGELOG.md
  main.go
  service/certificate.go
Labels: 9 Review Required, 9 Waiting for Jenkins
